[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"

[lib]
path = "wasm/src/lib.rs"
crate-type = ["cdylib", "rlib"]
